# Zoom
KP_SUBTRACT  	add video-zoom -.25
KP_ADD  	add video-zoom .25

KP_UP         add video-pan-y .05
KP_RIGHT         add video-pan-x -.05
KP_DOWN         add video-pan-y -.05
KP_LEFT         add video-pan-x .05

KP_BEGIN         set video-pan-x 0; set video-pan-y 0; set video-zoom 0
