#!/usr/bin/bash

# Policy Authentication Agent
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

if [[ ! `pidof hypridle` ]]; then
    hypridle >> /var/log/hypridle.log &
fi


# variables
scripts=~/.scripts
wallpapers=~/.wallpapers

# waybar
$scripts/launch_waybar &

# wallpaper
swww query || swww init

# clipboard
wl-paste --watch cliphist store &

# Applets
nm-applet &
blueman-applet &
