#!/usr/bin/bash

# Policy Authentication Agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# variables
scripts=~/.scripts

# waybar
$scripts/launch_waybar &

# wallpaper
$scripts/wall ~/.wallpapers/1.png &

# clipboard
wl-paste --watch cliphist store &

# Applets
nm-applet --indicator &
blueman-applet &
