#!/usr/bin/bash

killall -q waybar

# env GTK_DEBUG=interactive
waybar --log-level debug \
    --config ~/.config/waybar/config.jsonc \
    --style ~/.config/waybar/style.css > /tmp/waybar.log 2>&1 & disown
