#!/usr/bin/bash

swww_fork=~/.scripts/tools/swww

swww query || swww init
echo "Changing wallpaper to $1"
swww img "$1" \
    --transition-fps 60 \
    --transition-type grow \
    --transition-pos 0.925,0.977 \
    --transition-duration 2
