#!/usr/bin/bash

scripts=~/.scripts

cooldown=1

while true
do
    case "$1" in
        "arrow-icon")
            if $scripts/tools/toolbar_state; then
                echo '{"text":"","tooltip":"Collapse"}'
            else
                echo '{"text":"","tooltip":"Expand"}'
            fi
            ;;
        "ss-icon")
            if $scripts/tools/toolbar_state; then
                echo '{"text":"","tooltip":"Screenshot"}'
            else
                echo ""
            fi
            ;;
        "power")
            if $scripts/tools/toolbar_state; then
                echo '{"text":"⏻","tooltip":"Power"}'
            else
                echo ""
            fi
            ;;
        "clipboard")
            if $scripts/tools/toolbar_state; then
                echo '{"text":"","tooltip":"Clipboard | Nuke | Delete"}'
            else
                echo ""
            fi
            ;;
    esac
    sleep $cooldown
done
